# Generated by Selenium IDE
import pytest
import time
import json
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestReleaseClickOnLink(unittest.TestCase):
  def setUp(self):
    self.driver = webdriver.Chrome(executable_path='./chromedriver.exe')
    self.vars = {}
  
  def test_releaseClickOnLink(self):
    self.driver.get("http://localhost/CDP/src")
    self.driver.set_window_size(1900, 1020)
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, "#formCo > div:nth-child(3)").click()
    self.driver.find_element(By.ID, "nameCo").click()
    self.driver.find_element(By.ID, "nameCo").send_keys("TestAccountSelenium")
    self.driver.find_element(By.ID, "pswdCo").click()
    self.driver.find_element(By.ID, "pswdCo").send_keys("test")
    self.driver.find_element(By.NAME, "submitCo").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".d-inline-block").click()
    time.sleep(5)
    self.driver.find_element(By.ID, "releases").click()
    self.driver.find_element(By.ID, "link0").click()

  def tearDown(self):
    self.driver.quit() 
