# Generated by Selenium IDE
import pytest
import time
import json
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestSprintAddModifyDelete(unittest.TestCase):
  def setUp(self):
    self.driver = webdriver.Chrome(executable_path='./chromedriver.exe')
    self.vars = {}
  
  def test_sprintAddModifyDelete(self):
    self.driver.get("http://localhost/CDP/src")
    self.driver.set_window_size(1900, 1020)
    time.sleep(5)
    self.driver.find_element(By.ID, "nameCo").click()
    self.driver.find_element(By.ID, "nameCo").send_keys("TestAccountSelenium")
    self.driver.find_element(By.ID, "pswdCo").click()
    self.driver.find_element(By.ID, "pswdCo").send_keys("test")
    self.driver.find_element(By.NAME, "submitCo").click()
    time.sleep(5)
    self.driver.find_element(By.CSS_SELECTOR, ".d-inline-block").click()
    time.sleep(5)
    self.driver.find_element(By.ID, "sprints").click()
    time.sleep(5)
    self.driver.find_element(By.ID, "addButton").click()
    time.sleep(3)
    self.driver.find_element(By.ID, "sprintName").click()
    self.driver.find_element(By.ID, "sprintName").send_keys("Sprint1")
    self.driver.find_element(By.ID, "sprintStartDate").click()
    self.driver.find_element(By.ID, "sprintStartDate").send_keys("2019-11-22")
    self.driver.find_element(By.ID, "sprintEndDate").click()
    self.driver.find_element(By.ID, "sprintEndDate").send_keys("2019-11-29")
    self.driver.find_element(By.NAME, "submit").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    time.sleep(3)
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(4) > #sprintEndDate").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(4) > #sprintEndDate").send_keys("2019-11-28")
    self.driver.find_element(By.NAME, "modify").click()
    self.driver.find_element(By.NAME, "delete").click()

  def tearDown(self):
    self.driver.quit()
  
