# Generated by Selenium IDE
import pytest
import time
import json
import unittest
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys

class TestSprintAddModifyDelete(unittest.TestCase):
  def setup_method(self):
    self.driver = webdriver.Chrome()
  
  def teardown_method(self):
    self.driver.quit()
  
  def test_sprintAddModifyDelete(self):
    self.driver.get("http://localhost/CDP/app/")
    self.driver.set_window_size(1900, 1020)
    self.driver.find_element(By.ID, "nameCo").click()
    self.driver.find_element(By.ID, "nameCo").send_keys("TestAccount")
    self.driver.find_element(By.ID, "pswdCo").click()
    self.driver.find_element(By.ID, "pswdCo").send_keys("test")
    self.driver.find_element(By.NAME, "submitCo").click()
    self.driver.find_element(By.CSS_SELECTOR, ".d-inline-block").click()
    self.driver.find_element(By.LINK_TEXT, "Les sprints").click()
    self.driver.find_element(By.ID, "addButton").click()
    self.driver.find_element(By.ID, "sprintName").click()
    self.driver.find_element(By.ID, "sprintName").send_keys("Sprint de Test")
    self.driver.find_element(By.ID, "sprintStartDate").click()
    self.driver.find_element(By.ID, "sprintStartDate").send_keys("2019-11-05")
    self.driver.find_element(By.ID, "sprintEndDate").click()
    self.driver.find_element(By.ID, "sprintEndDate").send_keys("2019-11-12")
    self.driver.find_element(By.NAME, "submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(4) > #sprintEndDate").click()
    self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(4) > #sprintEndDate").send_keys("2019-11-13")
    self.driver.find_element(By.NAME, "modify").click()
    self.driver.find_element(By.NAME, "delete").click()
  
