version: '3.7'
services:
    db:
        build: 
            context: .
            dockerfile: Dockerfile_DB
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=root
        ports:
            - '3306:3306'
    app:
        build: .
        ports:
            - '80:80'
