version: '3'

services:
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        depends_on:
            - database
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
        restart: always

    database:
        build:
            context: .
            dockerfile: Dockerfile.bdd
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: aan
            MYSQL_DATABASE: cdp
            MYSQL_PASSWORD: aan
        ports:
            - 9906:3306

    web:
        build:
            context: .
        container_name: php
        ports:
            - 8100:80
        depends_on:
            - database
        links:
            - database
        volumes:
            - ./:/var/www/html/